### ISSUE TITLE
Optional profile for publishing?

### ISSUE THREAD

**Issue by pepoospina** [vemonet/nanopub-rs#4]
If a nanopublication is already signed, then the `publish` method don't really need a profile, but right now it is not an optional input on the JS implementation.

It also seems that, if you call publish over a signed nanopublication the `profile`, even if provided, is ignored.

**Comment by vemonet** [comment]
Hi @pepoospina, thanks for the feedback! Those are really good points, I always use it for signing and publishing so I did not notice these incoherences

It makes sense to make the profile optional for when the user wants to publish an already signed nanopub, this should be the expected behavior. I will do it next time I develop on the project

If you call publish over an already signed nanopublication, with a profile provided, indeed from a dev pov I would expect the nanopub to be re-signed with the provided profile. I'll check to fix this next time too

**Comment by vemonet** [comment]
Hi @pepoospina 

I fixed the 2 points, starting from version `0.1.0` you can skip providing a profile when publishing. I also improved the JS bindings to enable to pass `null` for the `profile` and `server_url` args (or just `.publish()`). 

The library will behave as follow:

- If signed nanopub and profile not provided, we publish the signed nanopub as it is
- If signed nanopub and profile provided, we re-sign the nanopub (only the triples related to the signature are changed).
- If unsigned nanopub and profile provided, we sign the nanopub
- If unsigned nanopub and profile not provided, we throw an error

There is now a new `.unsign()` function to convert a nanopub from signed to unsigned state available on the rust API. I can expose it to JS if needed, let me know

Thanks a lot for the reports, please send more if you are facing other issues or weird behaviors!
