### ISSUE TITLE
JavaScript examples blocked by CORS

### ISSUE THREAD

**Issue by mdroidian** [vemonet/nanopub-rs#9]
Trying both of the JavaScript examples:

https://vemonet.github.io/nanopub-rs/javascript-example-html/
https://vemonet.github.io/nanopub-rs/javascript-example-framework/

Both are blocked by CORS when trying:

`const np = await new Nanopub(rdf).publish(profile, serverUrl)`

![image](https://github.com/user-attachments/assets/6f1e5474-fb0c-4216-bb2d-17d637c4ab73)

**Comment by tkuhn** [comment]
Same as with the other issue (https://github.com/vemonet/nanopub-rs/issues/10) could be a problem on my side, but I am not sure. Could you share the full POST request/response headers?

**Comment by mdroidian** [comment]
Here's a video showing the whole Network tab of the html example

https://www.loom.com/share/db5a8c4e698549f9918ac1ada9709c2a

**Comment by tkuhn** [comment]
Same as for the other issue. This should be resolved, I hope.

**Comment by vemonet** [comment]
@mdroidian thanks a lot for reporting! 

Note that when getting errors related to CORS, to validate the problem is really related to CORS, or if you just need to get the thing done before the CORS policy is fixed on the server, you can bypass CORS blockages by installing an extension like [cors-everywhere](https://addons.mozilla.org/fr/firefox/addon/cors-everywhere/) and enabling CORS through this extension

**Comment by mdroidian** [comment]
Fixed, thanks!
